/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * 
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user guide at https://docs.gradle.org/4.9/userguide/multi_project_builds.html
 */
import org.gradle.kotlin.dsl.*
buildscript {
  repositories {
    jcenter()
  }
  dependencies {
    classpath ("net.saliman:gradle-properties-plugin:1.4.6")
  }

}
apply(plugin="net.saliman.properties")

rootProject.name = "ssi"
val includedev : String? by settings

if( includedev != null ) {
//  includeBuild("../../core-dsl")
//includeBuild("../../nconn-v2/client-dsl")
//  includeBuild("../../nconn-v2")
 // includeBuild("../../docstore")
//  includeBuild("../../maildb")
}
pluginManagement {
  repositories { 
     mavenLocal()
     gradlePluginPortal()
     maven { url = uri("build/repo" ) }
   }
}
sourceControl {
    vcsMappings {
    }
}
